version: '3.3'

services:

  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./expert_system/.env

  bot:
    build:
      context: ./bot/
    restart: always
    env_file:
      - ./bot/.env

  expert_system:
    build:
      context: ./expert_system/
    restart: always
    depends_on:
      - db
    env_file:
      - ./expert_system/.env

volumes:
  db_data:
