from telegram.ext import ConversationHandler

UNSUBSCRIBE = "UNSUBSCRIBE"
UNSUBSCRIBE_INFO = "UNSUBSCRIBE_INFO"
POSITION_RESULT = 'POSITION_RESULT'
POSITION_SUBSCRIBE = 'POSITION_SUBSCRIBE'
RATE_RESULT = 'RATE_RESULT'
STOCK_RESULT = 'STOCK_RESULT'
RATE_RESULT = 'RATE_RESULT'
END = ConversationHandler.END
