from telegram.ext import ConversationHandler


POSITION_RESULT = 'POSITION_RESULT'
POSITION_SUBSCRIBE = 'POSITION_SUBSCRIBE'
STOCK_RESULT = 'STOCK_RESULT'
RATE_RESULT = 'RATE_RESULT'
END = ConversationHandler.END
