# Generated by Django 4.2.2 on 2023-06-15 12:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cover_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_header', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('text', tinymce.models.HTMLField()),
                ('buttons', models.ManyToManyField(related_name='text', to='data_handler.button')),
            ],
        ),
        migrations.AddField(
            model_name='button',
            name='slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='button', to='data_handler.text'),
        ),
    ]
